import './style/globals.css'
// import './style/reset.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import StyledComponentsRegistry from '@/lib/AntdRegistery'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <StyledComponentsRegistry>{children}</StyledComponentsRegistry> */}
      <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
